---
title: "رؤية للاستشـارات"
format: 
  html: 
    template-partials:
    - title-block.html
title-block-banner: true
subtitle: "نُحوِّل بياناتك إلى قرارات"
image: ""
about: 
  template: jolla
  #image-shape: round
  #image-width: 7em
  # links:
  #   - icon: envelope
  #     text: Email
  #     #href: ""
  #   - icon: linkedin
  #     text: LinkedIn
  #     href: https://www.linkedin.com
  #     target: _blank
---

::: {.section-alt #about}

::: {.intro-quote .half-width}
نحن شركة استشارية متخصصة في علم البيانات والإحصاء، نعمل على تمكين الشركات من فهم بياناتها بشكل أعمق، وبناء قرارات أكثر وعيًا اعتمادًا على التحليل الدقيق والمنهجي.

نمتلك خبرة عملية في التعامل مع البيانات ضمن بيئات عمل مختلفة، ونركّز على تحويل البيانات الخام إلى معرفة واضحة يمكن الاعتماد عليها. نولي اهتمامًا خاصًا **بجودة التحليل**، **بساطة العرض**، **وموثوقية النتائج** بما يخدم أهداف العميل.

نلتزم بأعلى معايير سرية و**خصوصية البيانات**، ونعتبر حماية بيانات العملاء أولوية أساسية في جميع مراحل العمل. نعتمد على أدوات وتقنيات تحليل حديثة، ونمتلك خبرة في استخدام أدوات التحليل المتقدمة مثل R وPython وSQL وTableau وPower BI، مما يتيح لنا التعامل مع بيانات معقدة وبأحجام مختلفة، وتقديم مخرجات تحليلية واضحة وقابلة للتطبيق.
:::
:::

::: {.services-section #services}
## خدماتنـا
دعنا نساعدك على فهم بياناتك واتخاذ قرارات أفضل.

::: {.columns}

::: {.column width="30%"}

{{< fa chart-simple size = 3x >}} 
### خدمة التحليل الربع سنوي
تقارير ربع سنوية تساعدك على متابعة الأداء وفهم أرقامك بشكل واضح.
:::

::: {.column width="30%"}

{{< fa chalkboard size = 3x >}} 
### لوحات متابعة الأداء
لوحات معلومات تفاعلية تمكن الإدارة من متابعة المؤشرات بسهولة ووضوح.
:::

::: {.column width="30%"}

{{< fa magnifying-glass-chart size = 3x >}} 
### حلول تحليلية مخصصة
مشاريع مصممة لمعالجة تحديات محددة حسب احتياجات العميل.
:::

:::


:::

```{=html}
<div class="contact-section full-width-section">
  <h3 class="gradient-text">تواصل معنا</h3>

  <div class="contact-row">
    <i class="fa-solid fa-envelope"></i>
    <a href="mailto:contact@roya-consultancy.com">
      contact@roya-consultancy.com
    </a>
  </div>

  <div class="contact-row">
    <i class="fa-solid fa-phone"></i>
    <span class="phone">123456789</span>
  </div>

  <div class="contact-row">
    <i class="fa-solid fa-location-dot"></i>
    <span>الرياض، المملكة العربية السعودية</span>
  </div>

  <div class="contact-copyright">
  Copyright 2025, Roya Consultancy
  </div>
</div>

```




